import School from "@material-ui/icons/School";
import Work from '@mui/icons-material/Work';
import Resume from '../../../assets/Resume.png';

export let timelineElements = [
  {
    id: 1,
    title: 'Bachelor of Science',
    location: '@ University of Oregon',
    description: 'GSS with focus in Bus / Econ',
    buttonText: 'View Website',
    date: 'September 2015 - 2019',
    icon: 'School',
    link: 'https://www.uoregon.edu/',
  },
  {
    id: 2,
    title: 'Sales Development Representative',
    location: '@ Deltek',
    description: 'Professional role with daily  KPI’s, monthly quota (10), & cross sectional team.Responsible for outbound & inbound outreach, pipeline growth.',
    buttonText: 'View Website',
    date: 'March 2019 - March 2021',
    icon: 'Work',
    link: 'https://www.deltek.com/en',
  },
  {
    id: 3,
    title: 'Coding Bootcamp',
    location: '@ Epicodus',
    description: 'Certificate of Completion for 27 week bootcamp. Track was focused on the following:',
    points: ['- Javascript', '- React', '- C#', '- CSS & HTML'],
    buttonText: 'View Website',
    date: 'March 2021 - June 2021',
    icon: 'School',
    link: 'https://www.epicodus.com/',
  },
  {
    id: 4,
    title: 'Web Development Internship',
    location: '@ VALIDATE',
    description: 'Frontend React web application built to give early-stage companies more data to make informed decisions. Refactored from Alpha stage into a Beta version.',
    buttonText: 'View Website',
    date: 'June 2021 - August 2021',
    icon: 'Work',
    link: 'https://www.linkedin.com/company/validateclub/',
  },
  {
    id: 5,
    title: 'Responsive Web Design Fundamentals',
    location: '@ Udacity',
    description: 'Focused on what makes a site responsive and how common responsive design patterns work across different devices.',
    points: ['- Media Queries', '- Flexbox', '- Optimizations', '- Breakpoints', '- Common responsive patterns'],
    buttonText: '',
    date: 'December 2022',
    icon: 'Work',
    link: '',
  },
  {
    id: 6,
    title: 'React Web Developer',
    location: '@ Opine',
    description: 'React Application built for the Washington school district: empowers students to debate in a safe and exciting method.',
    buttonText: 'View Website',
    date: 'December 2022 - Present',
    icon: 'Work',
    link: 'https://opineschool.com/',
  },
  {
    id: 7,
    title: 'View',
    location: 'Resume',
    img: `${Resume}`,
    description: '',
    // buttonText: 'View Website',
    date: 'December 2022 - Present',
    icon: null,
    link: 'https://docs.google.com/document/d/1oaRwK2RvkR2c0hmXVDrE1k8jNoHA_CdWvMhrpSNsVuM/edit?usp=sharing',
  },
]